### ISSUE TITLE
Hyperparameter for pretraining primitive skills

### ISSUE THREAD

**Issue by tunglm2203** [clvrai/sprint#2]
Thank you for sharing the code.

I'm trying to pretrain primitive skills using IQL. I confused about the batch size you used for pretraining. In the paper, you mentioned bs=1024, however, in both code and released checkpoints, it's 64. So what exact batch size do you use for pretraining?

And, could you share the hardware spec you used for pretraining and how long it takes for pretraining?

Thank you.

**Comment by jesbu1** [comment]
Oops 1024 is wrong, it must be a leftover number from when the model was not a transformer but an MLP. 

The default parameters in the code are correct.

Pretraining takes about a day on a 3090 GPU when the data is saved to an SSD.

**Comment by tunglm2203** [comment]
Thank you for quick response!
