### ISSUE TITLE
Question about computing the reward in PickupObjectAction()

### ISSUE THREAD

**Issue by tunglm2203** [clvrai/sprint#3]
Hi,
"Hi, I'm evaluating the EVAL Instruction environment and noticed that in some tasks, the reward does not equal 1 even after the agent completes a skill.

For example, in _"pick_two_obj_and_place-PotatoSliced-None-SinkBasin-13/trial_T20190908_181751_435129"_ with 9 skills required (in this [line](https://github.com/clvrai/sprint/blob/62645ab5c2af74a65e23bed15a10222ceced1d32/sprint/rollouts/eval_instruct_ann_human.json#L7068)), the agent initially attempts to pick up a knife from the counter's corner. 

There are two knives at this location (Figure below), and ideally, picking up either shoud get a reward of 1. However, the reward function only returns 1 when picking the correct one based on the expert's demonstration, i.e., the innermost knife (see this [line](https://github.com/clvrai/sprint/blob/62645ab5c2af74a65e23bed15a10222ceced1d32/sprint/alfred/env/reward.py#L118)), while the outermost knife is also possible (and in your code, the agent selected the outermost one since it's closer distance, in [here](https://github.com/clvrai/sprint/blob/62645ab5c2af74a65e23bed15a10222ceced1d32/sprint/utils/utils.py#L414)). 

So, I think the agent will always fail in this scene. Do you have any idea to fix this situation?

![knifes_in_counter](https://github.com/clvrai/sprint/assets/38417805/73bcd6ec-0af1-4ec2-b903-8c199f2f5674)

**Comment by jesbu1** [comment]
Yes this is accurate, this is unfortunately a byproduct of ALFRED's built-in reward functions and how it checks for completion of tasks.

I have written code to get around this for BOSS, but I did not change it for SPRINT to be consistent with the existing results I have in the paper. Even then, it's quite a bit messy and amounts to a billion "if" statements that check for very certain edge cases to try to reward the agent correctly.

I'll share that code with you when BOSS is released, but it's going to be a bit different from SPRINT's implementation which follows more closely with ALFRED's original reward functions.
